dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    rooms:
      secure: TpuHRYhR29zE32EEmBl4ZH2LA8QctBe2zvcR+waDRDpY9LowygVzDRd7Futakb3UcF5e4yDn3PdYIS8kYliEjSqByk2JHF1deyEJOIvalPHgDKl6WuHmZieJkpE7u4Z/3HV0xELmiy3L6bG/amxH7b7lUO07kIR1keWrrW6lTX/f3p/KTH5BN/zVj/6rNwjffTIx+0lRqB6HT8G/i5QvGKfu4nx9aJTRNtyuVFy1B/judJHx3k2ENjrnWTCsRf+eS28svBieWGAetezAMb1sqB6ek6HhS0ut0wGtpqqsxqV/ITS5NCZFyOVi89fXzhgdCtKKI5oKh+jx+eJ/3UXii4G/xMMk/g4ZA+WuF8A7mdKZVdq6TrV3Dgd3iilozwAzoyb09/GYDk3CQ+XS6HSfJAMmksEhNjhpCEUu0Q72O3kSfMoT4rE3/3yLx41Q+ijLYfEJshbvrXDfMjWZRiBCFCMPQNABYvyWjaGerHOrX1mZRcAXMsbVs2hShKJBLz7wT8hi8PxdFrM1gwPSyAPI0Tjq4wNjEg3BcRDKyRP6YqgtXwe/g4dbC/KvJ2q53qVrCWWPnYTkX2zBJdBEdO+zwZQkCMkNEf2YsUMKTwQGTcgAu2c/W2ktHGKBsC117ySyBJqZA7aXsXjKrpKcviT+EzOoo1im7mxMC6v0N7hRhnk=
